language: rust
dist: bionic
sudo: required
rust:
  - beta
  - nightly
  - stable

cache:
  directories:
    - target

os:
  - linux
#  - osx

git:
  submodules: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic main"
        key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    packages:
      - lld

script:
  - cargo build --features static-link --verbose
  - cargo test --tests --features static-link --no-fail-fast -- --test-threads 1

env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
    - RUSTFLAGS="-C link-arg=-fuse-ld=lld"
