language: rust
dist: bionic
sudo: required
rust:
  - beta
  - nightly
  - stable

cache:
  directories:
    - target

os:
  - linux
  - osx

before_script:
  - git submodule update --init --recursive

script:
  - travis_wait 30 cargo test --features "static-link" -- --test-threads 1

env:
  global:
    - LD_LIBRARY_PATH: "/usr/local/lib"
