language: rust
dist: bionic
sudo: required
rust:
  - beta
  - nightly
  - stable

os:
  - linux
#  - osx

git:
  submodules: true

script:
  - PATH="${PWD}/scripts:$PATH" travis_wait cargo build --features static-link --verbose
  - PATH="${PWD}/scripts:$PATH" travis_wait cargo test --tests --features static-link --no-fail-fast -- --test-threads 1

env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
    # use shell wrapper for cc to fix link error
    # - RUSTFLAGS="-C link-arg=-fuse-ld=lld"
