language: rust
dist: bionic
sudo: required
rust:
  - beta
  - nightly
  - stable

os:
  - linux
#  - osx

git:
  submodules: true

script:
  - travis_wait cargo build --features static-link --verbose
  - travis_wait cargo build --features static-link --verbose
  - RUSTFLAGS="-C linker=${PWD}/scripts/cc" travis_wait cargo test --tests --features static-link --no-fail-fast

env:
  global:
    - RUST_TEST_THREADS=1
    # use shell wrapper for cc to fix link error
    # - RUSTFLAGS="-C link-arg=-fuse-ld=lld"
