language: rust
dist: bionic
sudo: required
rust:
  - beta
  - nightly
  - stable

cache:
  directories:
    - target

os:
  - linux
#  - osx

before_script:
  - sudo apt install lld
  - git submodule update --init --recursive

script:
  - cargo build --features static-link --verbose
  - cargo test --tests --features static-link --no-fail-fast -- --test-threads 1

env:
  global:
    - LD_LIBRARY_PATH: "/usr/local/lib"
    - RUSTFLAGS: "-C link-arg=-fuse-ld=lld"
