/* automatically generated by rust-bindgen */

pub const __GNUC_VA_LIST: ::std::os::raw::c_uint = 1;
pub const __WORDSIZE: ::std::os::raw::c_uint = 64;
pub const __DARWIN_ONLY_64_BIT_INO_T: ::std::os::raw::c_uint = 0;
pub const __DARWIN_ONLY_VERS_1050: ::std::os::raw::c_uint = 0;
pub const __DARWIN_ONLY_UNIX_CONFORMANCE: ::std::os::raw::c_uint = 1;
pub const __DARWIN_UNIX03: ::std::os::raw::c_uint = 1;
pub const __DARWIN_64_BIT_INO_T: ::std::os::raw::c_uint = 1;
pub const __DARWIN_VERS_1050: ::std::os::raw::c_uint = 1;
pub const __DARWIN_NON_CANCELABLE: ::std::os::raw::c_uint = 0;
pub const __DARWIN_SUF_64_BIT_INO_T: &'static [u8; 9usize] = b"$INODE64\x00";
pub const __DARWIN_SUF_1050: &'static [u8; 6usize] = b"$1050\x00";
pub const __DARWIN_SUF_EXTSN: &'static [u8; 14usize] = b"$DARWIN_EXTSN\x00";
pub const __DARWIN_C_ANSI: ::std::os::raw::c_uint = 4096;
pub const __DARWIN_C_FULL: ::std::os::raw::c_uint = 900000;
pub const __DARWIN_C_LEVEL: ::std::os::raw::c_uint = 900000;
pub const __STDC_WANT_LIB_EXT1__: ::std::os::raw::c_uint = 1;
pub const _DARWIN_FEATURE_64_BIT_INODE: ::std::os::raw::c_uint = 1;
pub const _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE: ::std::os::raw::c_uint = 1;
pub const _DARWIN_FEATURE_UNIX_CONFORMANCE: ::std::os::raw::c_uint = 3;
pub const __PTHREAD_SIZE__: ::std::os::raw::c_uint = 8176;
pub const __PTHREAD_ATTR_SIZE__: ::std::os::raw::c_uint = 56;
pub const __PTHREAD_MUTEXATTR_SIZE__: ::std::os::raw::c_uint = 8;
pub const __PTHREAD_MUTEX_SIZE__: ::std::os::raw::c_uint = 56;
pub const __PTHREAD_CONDATTR_SIZE__: ::std::os::raw::c_uint = 8;
pub const __PTHREAD_COND_SIZE__: ::std::os::raw::c_uint = 40;
pub const __PTHREAD_ONCE_SIZE__: ::std::os::raw::c_uint = 8;
pub const __PTHREAD_RWLOCK_SIZE__: ::std::os::raw::c_uint = 192;
pub const __PTHREAD_RWLOCKATTR_SIZE__: ::std::os::raw::c_uint = 16;
pub const INT8_MAX: ::std::os::raw::c_uint = 127;
pub const INT16_MAX: ::std::os::raw::c_uint = 32767;
pub const INT32_MAX: ::std::os::raw::c_uint = 2147483647;
pub const INT64_MAX: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const INT8_MIN: ::std::os::raw::c_int = -128;
pub const INT16_MIN: ::std::os::raw::c_int = -32768;
pub const INT32_MIN: ::std::os::raw::c_int = -2147483648;
pub const INT64_MIN: ::std::os::raw::c_longlong = -9223372036854775808;
pub const UINT8_MAX: ::std::os::raw::c_uint = 255;
pub const UINT16_MAX: ::std::os::raw::c_uint = 65535;
pub const UINT32_MAX: ::std::os::raw::c_uint = 4294967295;
pub const UINT64_MAX: ::std::os::raw::c_int = -1;
pub const INT_LEAST8_MIN: ::std::os::raw::c_int = -128;
pub const INT_LEAST16_MIN: ::std::os::raw::c_int = -32768;
pub const INT_LEAST32_MIN: ::std::os::raw::c_int = -2147483648;
pub const INT_LEAST64_MIN: ::std::os::raw::c_longlong = -9223372036854775808;
pub const INT_LEAST8_MAX: ::std::os::raw::c_uint = 127;
pub const INT_LEAST16_MAX: ::std::os::raw::c_uint = 32767;
pub const INT_LEAST32_MAX: ::std::os::raw::c_uint = 2147483647;
pub const INT_LEAST64_MAX: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const UINT_LEAST8_MAX: ::std::os::raw::c_uint = 255;
pub const UINT_LEAST16_MAX: ::std::os::raw::c_uint = 65535;
pub const UINT_LEAST32_MAX: ::std::os::raw::c_uint = 4294967295;
pub const UINT_LEAST64_MAX: ::std::os::raw::c_int = -1;
pub const INT_FAST8_MIN: ::std::os::raw::c_int = -128;
pub const INT_FAST16_MIN: ::std::os::raw::c_int = -32768;
pub const INT_FAST32_MIN: ::std::os::raw::c_int = -2147483648;
pub const INT_FAST64_MIN: ::std::os::raw::c_longlong = -9223372036854775808;
pub const INT_FAST8_MAX: ::std::os::raw::c_uint = 127;
pub const INT_FAST16_MAX: ::std::os::raw::c_uint = 32767;
pub const INT_FAST32_MAX: ::std::os::raw::c_uint = 2147483647;
pub const INT_FAST64_MAX: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const UINT_FAST8_MAX: ::std::os::raw::c_uint = 255;
pub const UINT_FAST16_MAX: ::std::os::raw::c_uint = 65535;
pub const UINT_FAST32_MAX: ::std::os::raw::c_uint = 4294967295;
pub const UINT_FAST64_MAX: ::std::os::raw::c_int = -1;
pub const INTPTR_MIN: ::std::os::raw::c_longlong = -9223372036854775808;
pub const INTPTR_MAX: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const UINTPTR_MAX: ::std::os::raw::c_int = -1;
pub const INTMAX_MIN: ::std::os::raw::c_longlong = -9223372036854775808;
pub const INTMAX_MAX: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const UINTMAX_MAX: ::std::os::raw::c_int = -1;
pub const PTRDIFF_MIN: ::std::os::raw::c_longlong = -9223372036854775808;
pub const PTRDIFF_MAX: ::std::os::raw::c_ulonglong = 9223372036854775807;
pub const SIZE_MAX: ::std::os::raw::c_int = -1;
pub const RSIZE_MAX: ::std::os::raw::c_int = -1;
pub const WINT_MIN: ::std::os::raw::c_int = -2147483648;
pub const WINT_MAX: ::std::os::raw::c_uint = 2147483647;
pub const SIG_ATOMIC_MIN: ::std::os::raw::c_int = -2147483648;
pub const SIG_ATOMIC_MAX: ::std::os::raw::c_uint = 2147483647;
pub type va_list = __builtin_va_list;
pub type __gnuc_va_list = __builtin_va_list;
pub type wchar_t = ::std::os::raw::c_int;
pub type max_align_t = f64;
pub type int_least8_t = i8;
pub type int_least16_t = i16;
pub type int_least32_t = i32;
pub type int_least64_t = i64;
pub type uint_least8_t = u8;
pub type uint_least16_t = u16;
pub type uint_least32_t = u32;
pub type uint_least64_t = u64;
pub type int_fast8_t = i8;
pub type int_fast16_t = i16;
pub type int_fast32_t = i32;
pub type int_fast64_t = i64;
pub type uint_fast8_t = u8;
pub type uint_fast16_t = u16;
pub type uint_fast32_t = u32;
pub type uint_fast64_t = u64;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_longlong;
pub type __uint64_t = ::std::os::raw::c_ulonglong;
pub type __darwin_intptr_t = ::std::os::raw::c_long;
pub type __darwin_natural_t = ::std::os::raw::c_uint;
pub type __darwin_ct_rune_t = ::std::os::raw::c_int;
#[repr(C)]
pub union __mbstate_t {
    pub __mbstate8: [::std::os::raw::c_char; 128usize],
    pub _mbstateL: ::std::os::raw::c_longlong,
}
pub type __darwin_mbstate_t = __mbstate_t;
pub type __darwin_ptrdiff_t = ::std::os::raw::c_long;
pub type __darwin_size_t = ::std::os::raw::c_ulong;
pub type __darwin_va_list = __builtin_va_list;
pub type __darwin_wchar_t = ::std::os::raw::c_int;
pub type __darwin_rune_t = __darwin_wchar_t;
pub type __darwin_wint_t = ::std::os::raw::c_int;
pub type __darwin_clock_t = ::std::os::raw::c_ulong;
pub type __darwin_socklen_t = __uint32_t;
pub type __darwin_ssize_t = ::std::os::raw::c_long;
pub type __darwin_time_t = ::std::os::raw::c_long;
pub type __darwin_blkcnt_t = __int64_t;
pub type __darwin_blksize_t = __int32_t;
pub type __darwin_dev_t = __int32_t;
pub type __darwin_fsblkcnt_t = ::std::os::raw::c_uint;
pub type __darwin_fsfilcnt_t = ::std::os::raw::c_uint;
pub type __darwin_gid_t = __uint32_t;
pub type __darwin_id_t = __uint32_t;
pub type __darwin_ino64_t = __uint64_t;
pub type __darwin_ino_t = __darwin_ino64_t;
pub type __darwin_mach_port_name_t = __darwin_natural_t;
pub type __darwin_mach_port_t = __darwin_mach_port_name_t;
pub type __darwin_mode_t = __uint16_t;
pub type __darwin_off_t = __int64_t;
pub type __darwin_pid_t = __int32_t;
pub type __darwin_sigset_t = __uint32_t;
pub type __darwin_suseconds_t = __int32_t;
pub type __darwin_uid_t = __uint32_t;
pub type __darwin_useconds_t = __uint32_t;
pub type __darwin_uuid_t = [::std::os::raw::c_uchar; 16usize];
pub type __darwin_uuid_string_t = [::std::os::raw::c_char; 37usize];
#[repr(C)]
#[derive(Copy)]
pub struct __darwin_pthread_handler_rec {
    pub __routine: ::std::option::Option<unsafe extern "C" fn(arg1:
                                                                  *mut ::std::os::raw::c_void)>,
    pub __arg: *mut ::std::os::raw::c_void,
    pub __next: *mut __darwin_pthread_handler_rec,
}
impl Clone for __darwin_pthread_handler_rec {
    fn clone(&self) -> Self { *self }
}
#[repr(C)]
pub struct _opaque_pthread_attr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 56usize],
}
#[repr(C)]
pub struct _opaque_pthread_cond_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 40usize],
}
#[repr(C)]
#[derive(Copy)]
pub struct _opaque_pthread_condattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
impl Clone for _opaque_pthread_condattr_t {
    fn clone(&self) -> Self { *self }
}
#[repr(C)]
pub struct _opaque_pthread_mutex_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 56usize],
}
#[repr(C)]
#[derive(Copy)]
pub struct _opaque_pthread_mutexattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
impl Clone for _opaque_pthread_mutexattr_t {
    fn clone(&self) -> Self { *self }
}
#[repr(C)]
#[derive(Copy)]
pub struct _opaque_pthread_once_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 8usize],
}
impl Clone for _opaque_pthread_once_t {
    fn clone(&self) -> Self { *self }
}
#[repr(C)]
pub struct _opaque_pthread_rwlock_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 192usize],
}
#[repr(C)]
#[derive(Copy)]
pub struct _opaque_pthread_rwlockattr_t {
    pub __sig: ::std::os::raw::c_long,
    pub __opaque: [::std::os::raw::c_char; 16usize],
}
impl Clone for _opaque_pthread_rwlockattr_t {
    fn clone(&self) -> Self { *self }
}
#[repr(C)]
pub struct _opaque_pthread_t {
    pub __sig: ::std::os::raw::c_long,
    pub __cleanup_stack: *mut __darwin_pthread_handler_rec,
    pub __opaque: [::std::os::raw::c_char; 8176usize],
}
pub type __darwin_pthread_attr_t = _opaque_pthread_attr_t;
pub type __darwin_pthread_cond_t = _opaque_pthread_cond_t;
pub type __darwin_pthread_condattr_t = _opaque_pthread_condattr_t;
pub type __darwin_pthread_key_t = ::std::os::raw::c_ulong;
pub type __darwin_pthread_mutex_t = _opaque_pthread_mutex_t;
pub type __darwin_pthread_mutexattr_t = _opaque_pthread_mutexattr_t;
pub type __darwin_pthread_once_t = _opaque_pthread_once_t;
pub type __darwin_pthread_rwlock_t = _opaque_pthread_rwlock_t;
pub type __darwin_pthread_rwlockattr_t = _opaque_pthread_rwlockattr_t;
pub type __darwin_pthread_t = *mut _opaque_pthread_t;
pub type intmax_t = ::std::os::raw::c_long;
pub type uintmax_t = ::std::os::raw::c_ulong;
#[repr(C)]
#[derive(Copy)]
pub struct Slice {
    pub data_: *const ::std::os::raw::c_char,
    pub size_: usize,
}
impl Clone for Slice {
    fn clone(&self) -> Self { *self }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rocks_column_family_descriptor_t([u8; 0]);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rocks_column_family_handle_t([u8; 0]);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rocks_db_t([u8; 0]);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rocks_cfoptions_t([u8; 0]);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rocks_dbpath_t([u8; 0]);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rocks_dboptions_t([u8; 0]);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rocks_options_t([u8; 0]);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rocks_readoptions_t([u8; 0]);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rocks_writeoptions_t([u8; 0]);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rocks_flushoptions_t([u8; 0]);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rocks_compactionoptions_t([u8; 0]);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rocks_compactrangeoptions_t([u8; 0]);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rocks_ingestexternalfileoptions_t([u8; 0]);
#[repr(C)]
#[derive(Copy)]
pub struct rocks_status_t {
    pub code: ::std::os::raw::c_int,
    pub sub_code: ::std::os::raw::c_int,
    pub state: *const ::std::os::raw::c_char,
}
impl Clone for rocks_status_t {
    fn clone(&self) -> Self { *self }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rocks_ratelimiter_t([u8; 0]);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rocks_envoptions_t([u8; 0]);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rocks_logger_t([u8; 0]);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rocks_env_t([u8; 0]);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rocks_snapshot_t([u8; 0]);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rocks_iterator_t([u8; 0]);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rocks_writebatch_t([u8; 0]);
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rocks_cache_t([u8; 0]);
extern "C" {
    pub fn rocks_options_create() -> *mut rocks_options_t;
}
extern "C" {
    pub fn rocks_options_destroy(options: *mut rocks_options_t);
}
extern "C" {
    pub fn rocks_dboptions_create() -> *mut rocks_dboptions_t;
}
extern "C" {
    pub fn rocks_dboptions_destroy(options: *mut rocks_dboptions_t);
}
extern "C" {
    pub fn rocks_cfoptions_create() -> *mut rocks_cfoptions_t;
}
extern "C" {
    pub fn rocks_cfoptions_destroy(options: *mut rocks_cfoptions_t);
}
extern "C" {
    pub fn rocks_options_create_from_db_cf_options(dbopt:
                                                       *mut rocks_dboptions_t,
                                                   cfopt:
                                                       *mut rocks_cfoptions_t)
     -> *mut rocks_options_t;
}
extern "C" {
    pub fn rocks_dboptions_create_from_options(options: *mut rocks_options_t)
     -> *mut rocks_dboptions_t;
}
extern "C" {
    pub fn rocks_cfoptions_create_from_options(options: *mut rocks_options_t)
     -> *mut rocks_cfoptions_t;
}
extern "C" {
    pub fn rocks_cfoptions_optimize_for_small_db(opt: *mut rocks_cfoptions_t);
}
extern "C" {
    pub fn rocks_cfoptions_optimize_for_point_lookup(opt:
                                                         *mut rocks_cfoptions_t,
                                                     block_cache_size_mb:
                                                         u64);
}
extern "C" {
    pub fn rocks_cfoptions_optimize_level_style_compaction(opt:
                                                               *mut rocks_cfoptions_t,
                                                           memtable_memory_budget:
                                                               u64);
}
extern "C" {
    pub fn rocks_cfoptions_optimize_universal_style_compaction(opt:
                                                                   *mut rocks_cfoptions_t,
                                                               memtable_memory_budget:
                                                                   u64);
}
extern "C" {
    pub fn rocks_cfoptions_set_write_buffer_size(opt: *mut rocks_cfoptions_t,
                                                 s: usize);
}
extern "C" {
    pub fn rocks_cfoptions_set_compression(opt: *mut rocks_cfoptions_t,
                                           t: ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_cfoptions_set_bottommost_compression(opt:
                                                          *mut rocks_cfoptions_t,
                                                      t:
                                                          ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_cfoptions_set_compression_options(opt:
                                                       *mut rocks_cfoptions_t,
                                                   w_bits:
                                                       ::std::os::raw::c_int,
                                                   level:
                                                       ::std::os::raw::c_int,
                                                   strategy:
                                                       ::std::os::raw::c_int,
                                                   max_dict_bytes: u32);
}
extern "C" {
    pub fn rocks_cfoptions_set_level0_file_num_compaction_trigger(opt:
                                                                      *mut rocks_cfoptions_t,
                                                                  n:
                                                                      ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_cfoptions_set_max_bytes_for_level_base(opt:
                                                            *mut rocks_cfoptions_t,
                                                        n: u64);
}
extern "C" {
    pub fn rocks_cfoptions_set_disable_auto_compactions(opt:
                                                            *mut rocks_cfoptions_t,
                                                        disable:
                                                            ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_cfoptions_set_plain_table_factory(opt:
                                                       *mut rocks_cfoptions_t,
                                                   user_key_len: u32,
                                                   bloom_bits_per_key:
                                                       ::std::os::raw::c_int,
                                                   hash_table_ratio: f64,
                                                   index_sparseness: usize);
}
extern "C" {
    pub fn rocks_cfoptions_set_max_write_buffer_number(opt:
                                                           *mut rocks_cfoptions_t,
                                                       n:
                                                           ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_cfoptions_set_min_write_buffer_number_to_merge(opt:
                                                                    *mut rocks_cfoptions_t,
                                                                n:
                                                                    ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_cfoptions_set_max_write_buffer_number_to_maintain(opt:
                                                                       *mut rocks_cfoptions_t,
                                                                   n:
                                                                       ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_cfoptions_set_inplace_update_support(opt:
                                                          *mut rocks_cfoptions_t,
                                                      v:
                                                          ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_cfoptions_set_inplace_update_num_locks(opt:
                                                            *mut rocks_cfoptions_t,
                                                        v: usize);
}
extern "C" {
    pub fn rocks_cfoptions_set_memtable_prefix_bloom_size_ratio(opt:
                                                                    *mut rocks_cfoptions_t,
                                                                v: f64);
}
extern "C" {
    pub fn rocks_cfoptions_set_memtable_huge_page_size(opt:
                                                           *mut rocks_cfoptions_t,
                                                       v: usize);
}
extern "C" {
    pub fn rocks_cfoptions_set_bloom_locality(opt: *mut rocks_cfoptions_t,
                                              v: u32);
}
extern "C" {
    pub fn rocks_cfoptions_set_arena_block_size(opt: *mut rocks_cfoptions_t,
                                                v: usize);
}
extern "C" {
    pub fn rocks_cfoptions_set_compression_per_level(opt:
                                                         *mut rocks_cfoptions_t,
                                                     level_values:
                                                         *const ::std::os::raw::c_int,
                                                     num_levels: usize);
}
extern "C" {
    pub fn rocks_cfoptions_set_num_levels(opt: *mut rocks_cfoptions_t,
                                          n: ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_cfoptions_set_level0_slowdown_writes_trigger(opt:
                                                                  *mut rocks_cfoptions_t,
                                                              n:
                                                                  ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_cfoptions_set_level0_stop_writes_trigger(opt:
                                                              *mut rocks_cfoptions_t,
                                                          n:
                                                              ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_cfoptions_set_target_file_size_base(opt:
                                                         *mut rocks_cfoptions_t,
                                                     n: u64);
}
extern "C" {
    pub fn rocks_cfoptions_set_target_file_size_multiplier(opt:
                                                               *mut rocks_cfoptions_t,
                                                           n:
                                                               ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_cfoptions_set_level_compaction_dynamic_level_bytes(opt:
                                                                        *mut rocks_cfoptions_t,
                                                                    v:
                                                                        ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_cfoptions_set_max_bytes_for_level_multiplier(opt:
                                                                  *mut rocks_cfoptions_t,
                                                              n: f64);
}
extern "C" {
    pub fn rocks_cfoptions_set_max_bytes_for_level_multiplier_additional(opt:
                                                                             *mut rocks_cfoptions_t,
                                                                         level_values:
                                                                             *mut ::std::os::raw::c_int,
                                                                         num_levels:
                                                                             usize);
}
extern "C" {
    pub fn rocks_cfoptions_set_max_compaction_bytes(opt:
                                                        *mut rocks_cfoptions_t,
                                                    n: u64);
}
extern "C" {
    pub fn rocks_cfoptions_set_soft_pending_compaction_bytes_limit(opt:
                                                                       *mut rocks_cfoptions_t,
                                                                   v: u64);
}
extern "C" {
    pub fn rocks_cfoptions_set_hard_pending_compaction_bytes_limit(opt:
                                                                       *mut rocks_cfoptions_t,
                                                                   v: u64);
}
extern "C" {
    pub fn rocks_cfoptions_set_compaction_style(opt: *mut rocks_cfoptions_t,
                                                style: ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_cfoptions_set_compaction_pri(opt: *mut rocks_cfoptions_t,
                                              pri: ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_cfoptions_set_max_sequential_skip_in_iterations(opt:
                                                                     *mut rocks_cfoptions_t,
                                                                 v: u64);
}
extern "C" {
    pub fn rocks_cfoptions_set_memtable_vector_rep(opt:
                                                       *mut rocks_cfoptions_t);
}
extern "C" {
    pub fn rocks_cfoptions_set_hash_skip_list_rep(opt: *mut rocks_cfoptions_t,
                                                  bucket_count: usize,
                                                  skiplist_height: i32,
                                                  skiplist_branching_factor:
                                                      i32);
}
extern "C" {
    pub fn rocks_cfoptions_set_hash_link_list_rep(opt: *mut rocks_cfoptions_t,
                                                  bucket_count: usize);
}
extern "C" {
    pub fn rocks_cfoptions_set_max_successive_merges(opt:
                                                         *mut rocks_cfoptions_t,
                                                     v: usize);
}
extern "C" {
    pub fn rocks_cfoptions_set_optimize_filters_for_hits(opt:
                                                             *mut rocks_cfoptions_t,
                                                         v:
                                                             ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_cfoptions_set_paranoid_file_checks(opt:
                                                        *mut rocks_cfoptions_t,
                                                    v:
                                                        ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_cfoptions_set_force_consistency_checks(opt:
                                                            *mut rocks_cfoptions_t,
                                                        v:
                                                            ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_cfoptions_set_report_bg_io_stats(opt: *mut rocks_cfoptions_t,
                                                  v: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_dboptions_optimize_for_small_db(opt: *mut rocks_dboptions_t);
}
extern "C" {
    pub fn rocks_dboptions_increase_parallelism(opt: *mut rocks_dboptions_t,
                                                total_threads:
                                                    ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_dboptions_set_create_if_missing(opt: *mut rocks_dboptions_t,
                                                 v: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_dboptions_set_create_missing_column_families(opt:
                                                                  *mut rocks_dboptions_t,
                                                              v:
                                                                  ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_dboptions_set_error_if_exists(opt: *mut rocks_dboptions_t,
                                               v: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_dboptions_set_paranoid_checks(opt: *mut rocks_dboptions_t,
                                               v: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_dboptions_set_env(opt: *mut rocks_dboptions_t,
                                   env: *mut rocks_env_t);
}
extern "C" {
    pub fn rocks_dboptions_set_ratelimiter(opt: *mut rocks_dboptions_t,
                                           limiter: *mut rocks_ratelimiter_t);
}
extern "C" {
    pub fn rocks_dboptions_set_info_log(opt: *mut rocks_dboptions_t,
                                        l: *mut rocks_logger_t);
}
extern "C" {
    pub fn rocks_dboptions_set_info_log_level(opt: *mut rocks_dboptions_t,
                                              v: ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_dboptions_set_max_open_files(opt: *mut rocks_dboptions_t,
                                              n: ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_dboptions_set_max_file_opening_threads(opt:
                                                            *mut rocks_dboptions_t,
                                                        n:
                                                            ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_dboptions_set_max_total_wal_size(opt: *mut rocks_dboptions_t,
                                                  n: u64);
}
extern "C" {
    pub fn rocks_dboptions_enable_statistics(opt: *mut rocks_dboptions_t);
}
extern "C" {
    pub fn rocks_dboptions_set_use_fsync(opt: *mut rocks_dboptions_t,
                                         use_fsync: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_dboptions_set_db_paths(opt: *mut rocks_dboptions_t,
                                        paths:
                                            *const *const ::std::os::raw::c_char,
                                        target_sizes: *const u64,
                                        size: ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_dboptions_set_db_log_dir(opt: *mut rocks_dboptions_t,
                                          db_log_dir:
                                              *const ::std::os::raw::c_char,
                                          len: usize);
}
extern "C" {
    pub fn rocks_dboptions_set_wal_dir(opt: *mut rocks_dboptions_t,
                                       v: *const ::std::os::raw::c_char,
                                       len: usize);
}
extern "C" {
    pub fn rocks_dboptions_set_delete_obsolete_files_period_micros(opt:
                                                                       *mut rocks_dboptions_t,
                                                                   v: u64);
}
extern "C" {
    pub fn rocks_dboptions_set_base_background_compactions(opt:
                                                               *mut rocks_dboptions_t,
                                                           n:
                                                               ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_dboptions_set_max_background_compactions(opt:
                                                              *mut rocks_dboptions_t,
                                                          n:
                                                              ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_dboptions_set_max_subcompactions(opt: *mut rocks_dboptions_t,
                                                  n: u32);
}
extern "C" {
    pub fn rocks_dboptions_set_max_background_flushes(opt:
                                                          *mut rocks_dboptions_t,
                                                      n:
                                                          ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_dboptions_set_max_log_file_size(opt: *mut rocks_dboptions_t,
                                                 v: usize);
}
extern "C" {
    pub fn rocks_dboptions_set_log_file_time_to_roll(opt:
                                                         *mut rocks_dboptions_t,
                                                     v: usize);
}
extern "C" {
    pub fn rocks_dboptions_set_keep_log_file_num(opt: *mut rocks_dboptions_t,
                                                 v: usize);
}
extern "C" {
    pub fn rocks_dboptions_set_recycle_log_file_num(opt:
                                                        *mut rocks_dboptions_t,
                                                    v: usize);
}
extern "C" {
    pub fn rocks_dboptions_set_max_manifest_file_size(opt:
                                                          *mut rocks_dboptions_t,
                                                      v: u64);
}
extern "C" {
    pub fn rocks_dboptions_set_table_cache_numshardbits(opt:
                                                            *mut rocks_dboptions_t,
                                                        v:
                                                            ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_dboptions_set_wal_ttl_seconds(opt: *mut rocks_dboptions_t,
                                               ttl: u64);
}
extern "C" {
    pub fn rocks_dboptions_set_wal_size_limit_mb(opt: *mut rocks_dboptions_t,
                                                 limit: u64);
}
extern "C" {
    pub fn rocks_dboptions_set_manifest_preallocation_size(opt:
                                                               *mut rocks_dboptions_t,
                                                           v: usize);
}
extern "C" {
    pub fn rocks_dboptions_set_allow_mmap_reads(opt: *mut rocks_dboptions_t,
                                                v: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_dboptions_set_allow_mmap_writes(opt: *mut rocks_dboptions_t,
                                                 v: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_dboptions_set_use_direct_reads(opt: *mut rocks_dboptions_t,
                                                v: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_dboptions_set_use_direct_writes(opt: *mut rocks_dboptions_t,
                                                 v: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_dboptions_set_allow_fallocate(opt: *mut rocks_dboptions_t,
                                               v: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_dboptions_set_is_fd_close_on_exec(opt:
                                                       *mut rocks_dboptions_t,
                                                   v:
                                                       ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_dboptions_set_stats_dump_period_sec(opt:
                                                         *mut rocks_dboptions_t,
                                                     v:
                                                         ::std::os::raw::c_uint);
}
extern "C" {
    pub fn rocks_dboptions_set_advise_random_on_open(opt:
                                                         *mut rocks_dboptions_t,
                                                     v:
                                                         ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_dboptions_set_db_write_buffer_size(opt:
                                                        *mut rocks_dboptions_t,
                                                    s: usize);
}
extern "C" {
    pub fn rocks_dboptions_set_access_hint_on_compaction_start(opt:
                                                                   *mut rocks_dboptions_t,
                                                               v:
                                                                   ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_dboptions_set_new_table_reader_for_compaction_inputs(opt:
                                                                          *mut rocks_dboptions_t,
                                                                      v:
                                                                          ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_dboptions_set_compaction_readahead_size(opt:
                                                             *mut rocks_dboptions_t,
                                                         s: usize);
}
extern "C" {
    pub fn rocks_dboptions_set_random_access_max_buffer_size(opt:
                                                                 *mut rocks_dboptions_t,
                                                             s: usize);
}
extern "C" {
    pub fn rocks_dboptions_set_writable_file_max_buffer_size(opt:
                                                                 *mut rocks_dboptions_t,
                                                             s: usize);
}
extern "C" {
    pub fn rocks_dboptions_set_use_adaptive_mutex(opt: *mut rocks_dboptions_t,
                                                  v: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_dboptions_set_bytes_per_sync(opt: *mut rocks_dboptions_t,
                                              v: u64);
}
extern "C" {
    pub fn rocks_dboptions_set_wal_bytes_per_sync(opt: *mut rocks_dboptions_t,
                                                  v: u64);
}
extern "C" {
    pub fn rocks_dboptions_set_enable_thread_tracking(opt:
                                                          *mut rocks_dboptions_t,
                                                      v:
                                                          ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_dboptions_set_delayed_write_rate(opt: *mut rocks_dboptions_t,
                                                  v: u64);
}
extern "C" {
    pub fn rocks_dboptions_set_allow_concurrent_memtable_write(opt:
                                                                   *mut rocks_dboptions_t,
                                                               v:
                                                                   ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_dboptions_set_enable_write_thread_adaptive_yield(opt:
                                                                      *mut rocks_dboptions_t,
                                                                  v:
                                                                      ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_dboptions_set_write_thread_max_yield_usec(opt:
                                                               *mut rocks_dboptions_t,
                                                           v: u64);
}
extern "C" {
    pub fn rocks_dboptions_set_write_thread_slow_yield_usec(opt:
                                                                *mut rocks_dboptions_t,
                                                            v: u64);
}
extern "C" {
    pub fn rocks_dboptions_set_skip_stats_update_on_db_open(opt:
                                                                *mut rocks_dboptions_t,
                                                            v:
                                                                ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_dboptions_set_wal_recovery_mode(opt: *mut rocks_dboptions_t,
                                                 mode: ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_dboptions_set_allow_2pc(opt: *mut rocks_dboptions_t,
                                         v: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_dboptions_set_row_cache(opt: *mut rocks_dboptions_t,
                                         cache: *mut rocks_cache_t);
}
extern "C" {
    pub fn rocks_dboptions_set_fail_if_options_file_error(opt:
                                                              *mut rocks_dboptions_t,
                                                          v:
                                                              ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_dboptions_set_dump_malloc_stats(opt: *mut rocks_dboptions_t,
                                                 v: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_dboptions_set_avoid_flush_during_recovery(opt:
                                                               *mut rocks_dboptions_t,
                                                           v:
                                                               ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_dboptions_set_avoid_flush_during_shutdown(opt:
                                                               *mut rocks_dboptions_t,
                                                           v:
                                                               ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_options_prepare_for_bulk_load(opt: *mut rocks_options_t);
}
extern "C" {
    pub fn rocks_options_optimize_for_small_db(opt: *mut rocks_options_t);
}
extern "C" {
    pub fn rocks_readoptions_create() -> *mut rocks_readoptions_t;
}
extern "C" {
    pub fn rocks_readoptions_destroy(opt: *mut rocks_readoptions_t);
}
extern "C" {
    pub fn rocks_readoptions_set_verify_checksums(opt:
                                                      *mut rocks_readoptions_t,
                                                  v: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_readoptions_set_fill_cache(opt: *mut rocks_readoptions_t,
                                            v: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_readoptions_set_snapshot(opt: *mut rocks_readoptions_t,
                                          snap: *const rocks_snapshot_t);
}
extern "C" {
    pub fn rocks_readoptions_set_iterate_upper_bound(opt:
                                                         *mut rocks_readoptions_t,
                                                     key:
                                                         *const ::std::os::raw::c_char,
                                                     keylen: usize);
}
extern "C" {
    pub fn rocks_readoptions_set_read_tier(opt: *mut rocks_readoptions_t,
                                           v: ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_readoptions_set_tailing(opt: *mut rocks_readoptions_t,
                                         v: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_readoptions_set_managed(opt: *mut rocks_readoptions_t,
                                         v: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_readoptions_set_readahead_size(opt: *mut rocks_readoptions_t,
                                                v: usize);
}
extern "C" {
    pub fn rocks_readoptions_set_pin_data(opt: *mut rocks_readoptions_t,
                                          v: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_readoptions_set_total_order_seek(opt:
                                                      *mut rocks_readoptions_t,
                                                  v: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_readoptions_set_prefix_same_as_start(opt:
                                                          *mut rocks_readoptions_t,
                                                      v:
                                                          ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_readoptions_set_ignore_range_deletions(opt:
                                                            *mut rocks_readoptions_t,
                                                        v:
                                                            ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_readoptions_set_background_purge_on_iterator_cleanup(opt:
                                                                          *mut rocks_readoptions_t,
                                                                      v:
                                                                          ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_writeoptions_create() -> *mut rocks_writeoptions_t;
}
extern "C" {
    pub fn rocks_writeoptions_destroy(opt: *mut rocks_writeoptions_t);
}
extern "C" {
    pub fn rocks_writeoptions_set_sync(opt: *mut rocks_writeoptions_t,
                                       v: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_writeoptions_set_disable_wal(opt: *mut rocks_writeoptions_t,
                                              v: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_writeoptions_set_ignore_missing_column_families(opt:
                                                                     *mut rocks_writeoptions_t,
                                                                 v:
                                                                     ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_writeoptions_set_no_slowdown(opt: *mut rocks_writeoptions_t,
                                              v: ::std::os::raw::c_uchar);
}
extern "C" {
    pub fn rocks_create_logger_from_options(path:
                                                *const ::std::os::raw::c_char,
                                            opts: *mut rocks_options_t,
                                            status: *mut rocks_status_t)
     -> *mut rocks_logger_t;
}
extern "C" {
    pub fn rocks_column_family_handle_get_name(handle:
                                                   *const rocks_column_family_handle_t)
     -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn rocks_column_family_handle_get_id(handle:
                                                 *const rocks_column_family_handle_t)
     -> u32;
}
extern "C" {
    pub fn rocks_db_open(options: *const rocks_options_t,
                         name: *const ::std::os::raw::c_char,
                         status: *mut rocks_status_t) -> *mut rocks_db_t;
}
extern "C" {
    pub fn rocks_db_open_for_read_only(options: *const rocks_options_t,
                                       name: *const ::std::os::raw::c_char,
                                       error_if_log_file_exist:
                                           ::std::os::raw::c_uchar,
                                       status: *mut rocks_status_t)
     -> *mut rocks_db_t;
}
extern "C" {
    pub fn rocks_db_close(db: *mut rocks_db_t);
}
extern "C" {
    pub fn rocks_db_open_column_families(db_options: *const rocks_options_t,
                                         name: *const ::std::os::raw::c_char,
                                         num_column_families:
                                             ::std::os::raw::c_int,
                                         column_family_names:
                                             *const *const ::std::os::raw::c_char,
                                         column_family_options:
                                             *const *const rocks_cfoptions_t,
                                         column_family_handles:
                                             *mut *mut rocks_column_family_handle_t,
                                         status: *mut rocks_status_t)
     -> *mut rocks_db_t;
}
extern "C" {
    pub fn rocks_db_open_for_read_only_column_families(db_options:
                                                           *const rocks_options_t,
                                                       name:
                                                           *const ::std::os::raw::c_char,
                                                       num_column_families:
                                                           ::std::os::raw::c_int,
                                                       column_family_names:
                                                           *mut *const ::std::os::raw::c_char,
                                                       column_family_options:
                                                           *mut *const rocks_cfoptions_t,
                                                       column_family_handles:
                                                           *mut *mut rocks_column_family_handle_t,
                                                       error_if_log_file_exist:
                                                           ::std::os::raw::c_uchar,
                                                       status:
                                                           *mut rocks_status_t)
     -> *mut rocks_db_t;
}
extern "C" {
    pub fn rocks_db_list_column_families(options: *const rocks_options_t,
                                         name: *const ::std::os::raw::c_char,
                                         lencfs: *mut usize,
                                         status: *mut rocks_status_t)
     -> *mut *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn rocks_db_list_column_families_destroy(list:
                                                     *mut *mut ::std::os::raw::c_char,
                                                 len: usize);
}
extern "C" {
    pub fn rocks_db_create_column_family(db: *mut rocks_db_t,
                                         column_family_options:
                                             *const rocks_cfoptions_t,
                                         column_family_name:
                                             *const ::std::os::raw::c_char,
                                         status: *mut rocks_status_t)
     -> *mut rocks_column_family_handle_t;
}
extern "C" {
    pub fn rocks_db_drop_column_family(db: *mut rocks_db_t,
                                       handle:
                                           *mut rocks_column_family_handle_t,
                                       status: *mut rocks_status_t);
}
extern "C" {
    pub fn rocks_db_destroy_column_family_handle(db: *mut rocks_db_t,
                                                 handle:
                                                     *mut rocks_column_family_handle_t,
                                                 status: *mut rocks_status_t);
}
extern "C" {
    pub fn rocks_column_family_handle_destroy(handle:
                                                  *mut rocks_column_family_handle_t);
}
extern "C" {
    pub fn rocks_db_put(db: *mut rocks_db_t,
                        options: *const rocks_writeoptions_t,
                        key: *const ::std::os::raw::c_char, keylen: usize,
                        val: *const ::std::os::raw::c_char, vallen: usize,
                        status: *mut rocks_status_t);
}
extern "C" {
    pub fn rocks_db_put_cf(db: *mut rocks_db_t,
                           options: *const rocks_writeoptions_t,
                           column_family: *mut rocks_column_family_handle_t,
                           key: *const ::std::os::raw::c_char, keylen: usize,
                           val: *const ::std::os::raw::c_char, vallen: usize,
                           status: *mut rocks_status_t);
}
extern "C" {
    pub fn rocks_db_delete(db: *mut rocks_db_t,
                           options: *const rocks_writeoptions_t,
                           key: *const ::std::os::raw::c_char, keylen: usize,
                           status: *mut rocks_status_t);
}
extern "C" {
    pub fn rocks_db_delete_cf(db: *mut rocks_db_t,
                              options: *const rocks_writeoptions_t,
                              column_family:
                                  *mut rocks_column_family_handle_t,
                              key: *const ::std::os::raw::c_char,
                              keylen: usize, status: *mut rocks_status_t);
}
extern "C" {
    pub fn rocks_db_single_delete(db: *mut rocks_db_t,
                                  options: *const rocks_writeoptions_t,
                                  key: *const ::std::os::raw::c_char,
                                  keylen: usize, status: *mut rocks_status_t);
}
extern "C" {
    pub fn rocks_db_single_delete_cf(db: *mut rocks_db_t,
                                     options: *const rocks_writeoptions_t,
                                     column_family:
                                         *mut rocks_column_family_handle_t,
                                     key: *const ::std::os::raw::c_char,
                                     keylen: usize,
                                     status: *mut rocks_status_t);
}
extern "C" {
    pub fn rocks_db_delete_range_cf(db: *mut rocks_db_t,
                                    options: *const rocks_writeoptions_t,
                                    column_family:
                                        *mut rocks_column_family_handle_t,
                                    begin_key: *const ::std::os::raw::c_char,
                                    begin_keylen: usize,
                                    end_key: *const ::std::os::raw::c_char,
                                    end_keylen: usize,
                                    status: *mut rocks_status_t);
}
extern "C" {
    pub fn rocks_db_merge(db: *mut rocks_db_t,
                          options: *const rocks_writeoptions_t,
                          key: *const ::std::os::raw::c_char, keylen: usize,
                          val: *const ::std::os::raw::c_char, vallen: usize,
                          status: *mut rocks_status_t);
}
extern "C" {
    pub fn rocks_db_merge_cf(db: *mut rocks_db_t,
                             options: *const rocks_writeoptions_t,
                             column_family: *mut rocks_column_family_handle_t,
                             key: *const ::std::os::raw::c_char,
                             keylen: usize,
                             val: *const ::std::os::raw::c_char,
                             vallen: usize, status: *mut rocks_status_t);
}
extern "C" {
    pub fn rocks_db_write(db: *mut rocks_db_t,
                          options: *const rocks_writeoptions_t,
                          batch: *mut rocks_writebatch_t,
                          status: *mut rocks_status_t);
}
extern "C" {
    pub fn rocks_db_get(db: *mut rocks_db_t,
                        options: *const rocks_readoptions_t,
                        key: *const ::std::os::raw::c_char, keylen: usize,
                        vallen: *mut usize, status: *mut rocks_status_t)
     -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn rocks_db_get_cf(db: *mut rocks_db_t,
                           options: *const rocks_readoptions_t,
                           column_family: *mut rocks_column_family_handle_t,
                           key: *const ::std::os::raw::c_char, keylen: usize,
                           vallen: *mut usize, status: *mut rocks_status_t)
     -> *mut ::std::os::raw::c_char;
}
extern "C" {
    pub fn rocks_db_multi_get(db: *mut rocks_db_t,
                              options: *const rocks_readoptions_t,
                              num_keys: usize,
                              keys_list: *const *const ::std::os::raw::c_char,
                              keys_list_sizes: *const usize,
                              values_list: *mut *mut ::std::os::raw::c_char,
                              values_list_sizes: *mut usize,
                              status: *mut rocks_status_t);
}
extern "C" {
    pub fn rocks_db_multi_get_cf(db: *mut rocks_db_t,
                                 options: *const rocks_readoptions_t,
                                 column_families:
                                     *const *const rocks_column_family_handle_t,
                                 num_keys: usize,
                                 keys_list:
                                     *const *const ::std::os::raw::c_char,
                                 keys_list_sizes: *const usize,
                                 values_list:
                                     *mut *mut ::std::os::raw::c_char,
                                 values_list_sizes: *mut usize,
                                 status: *mut rocks_status_t);
}
extern "C" {
    pub fn rocks_db_create_iterator(db: *mut rocks_db_t,
                                    options: *const rocks_readoptions_t)
     -> *mut rocks_iterator_t;
}
extern "C" {
    pub fn rocks_db_create_iterator_cf(db: *mut rocks_db_t,
                                       options: *const rocks_readoptions_t,
                                       column_family:
                                           *mut rocks_column_family_handle_t)
     -> *mut rocks_iterator_t;
}
extern "C" {
    pub fn rocks_db_create_iterators(db: *mut rocks_db_t,
                                     opts: *mut rocks_readoptions_t,
                                     column_families:
                                         *mut *mut rocks_column_family_handle_t,
                                     iterators: *mut *mut rocks_iterator_t,
                                     size: usize,
                                     status: *mut rocks_status_t);
}
extern "C" {
    pub fn rocks_db_get_snapshot(db: *mut rocks_db_t)
     -> *mut rocks_snapshot_t;
}
extern "C" {
    pub fn rocks_db_release_snapshot(db: *mut rocks_db_t,
                                     snapshot: *mut rocks_snapshot_t);
}
extern "C" {
    pub fn rocks_destroy_db(options: *const rocks_options_t,
                            name: *const ::std::os::raw::c_char,
                            status: *mut rocks_status_t);
}
extern "C" {
    pub fn rocks_repair_db(options: *const rocks_options_t,
                           name: *const ::std::os::raw::c_char,
                           status: *mut rocks_status_t);
}
extern "C" {
    pub fn rocks_ratelimiter_create(rate_bytes_per_sec: i64,
                                    refill_period_us: i64, fairness: i32)
     -> *mut rocks_ratelimiter_t;
}
extern "C" {
    pub fn rocks_ratelimiter_destroy(limiter: *mut rocks_ratelimiter_t);
}
extern "C" {
    pub fn rocks_create_default_env() -> *mut rocks_env_t;
}
extern "C" {
    pub fn rocks_create_mem_env() -> *mut rocks_env_t;
}
extern "C" {
    pub fn rocks_env_set_background_threads(env: *mut rocks_env_t,
                                            n: ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_env_set_high_priority_background_threads(env:
                                                              *mut rocks_env_t,
                                                          n:
                                                              ::std::os::raw::c_int);
}
extern "C" {
    pub fn rocks_env_join_all_threads(env: *mut rocks_env_t);
}
extern "C" {
    pub fn rocks_env_destroy(env: *mut rocks_env_t);
}
extern "C" {
    pub fn rocks_envoptions_create() -> *mut rocks_envoptions_t;
}
extern "C" {
    pub fn rocks_envoptions_destroy(opt: *mut rocks_envoptions_t);
}
extern "C" {
    pub fn rocks_logger_destroy(logger: *mut rocks_logger_t);
}
extern "C" {
    pub fn rocks_create_snapshot(db: *mut rocks_db_t)
     -> *const rocks_snapshot_t;
}
extern "C" {
    pub fn rocks_release_snapshot(db: *mut rocks_db_t,
                                  snapshot: *const rocks_snapshot_t);
}
extern "C" {
    pub fn rocks_writebatch_create() -> *mut rocks_writebatch_t;
}
extern "C" {
    pub fn rocks_writebatch_create_from(rep: *const ::std::os::raw::c_char,
                                        size: usize)
     -> *mut rocks_writebatch_t;
}
extern "C" {
    pub fn rocks_writebatch_destroy(b: *mut rocks_writebatch_t);
}
extern "C" {
    pub fn rocks_writebatch_clear(b: *mut rocks_writebatch_t);
}
extern "C" {
    pub fn rocks_writebatch_count(b: *mut rocks_writebatch_t)
     -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn rocks_writebatch_put(b: *mut rocks_writebatch_t,
                                key: *const ::std::os::raw::c_char,
                                klen: usize,
                                val: *const ::std::os::raw::c_char,
                                vlen: usize);
}
extern "C" {
    pub fn rocks_writebatch_put_cf(b: *mut rocks_writebatch_t,
                                   column_family:
                                       *mut rocks_column_family_handle_t,
                                   key: *const ::std::os::raw::c_char,
                                   klen: usize,
                                   val: *const ::std::os::raw::c_char,
                                   vlen: usize);
}
extern "C" {
    pub fn rocks_writebatch_putv(b: *mut rocks_writebatch_t,
                                 num_keys: ::std::os::raw::c_int,
                                 keys_list:
                                     *const *const ::std::os::raw::c_char,
                                 keys_list_sizes: *const usize,
                                 num_values: ::std::os::raw::c_int,
                                 values_list:
                                     *const *const ::std::os::raw::c_char,
                                 values_list_sizes: *const usize);
}
extern "C" {
    pub fn rocks_writebatch_putv_cf(b: *mut rocks_writebatch_t,
                                    column_family:
                                        *mut rocks_column_family_handle_t,
                                    num_keys: ::std::os::raw::c_int,
                                    keys_list:
                                        *const *const ::std::os::raw::c_char,
                                    keys_list_sizes: *const usize,
                                    num_values: ::std::os::raw::c_int,
                                    values_list:
                                        *const *const ::std::os::raw::c_char,
                                    values_list_sizes: *const usize);
}
extern "C" {
    pub fn rocks_writebatch_merge(b: *mut rocks_writebatch_t,
                                  key: *const ::std::os::raw::c_char,
                                  klen: usize,
                                  val: *const ::std::os::raw::c_char,
                                  vlen: usize);
}
extern "C" {
    pub fn rocks_writebatch_merge_cf(b: *mut rocks_writebatch_t,
                                     column_family:
                                         *mut rocks_column_family_handle_t,
                                     key: *const ::std::os::raw::c_char,
                                     klen: usize,
                                     val: *const ::std::os::raw::c_char,
                                     vlen: usize);
}
extern "C" {
    pub fn rocks_writebatch_mergev(b: *mut rocks_writebatch_t,
                                   num_keys: ::std::os::raw::c_int,
                                   keys_list:
                                       *const *const ::std::os::raw::c_char,
                                   keys_list_sizes: *const usize,
                                   num_values: ::std::os::raw::c_int,
                                   values_list:
                                       *const *const ::std::os::raw::c_char,
                                   values_list_sizes: *const usize);
}
extern "C" {
    pub fn rocks_writebatch_mergev_cf(b: *mut rocks_writebatch_t,
                                      column_family:
                                          *mut rocks_column_family_handle_t,
                                      num_keys: ::std::os::raw::c_int,
                                      keys_list:
                                          *const *const ::std::os::raw::c_char,
                                      keys_list_sizes: *const usize,
                                      num_values: ::std::os::raw::c_int,
                                      values_list:
                                          *const *const ::std::os::raw::c_char,
                                      values_list_sizes: *const usize);
}
extern "C" {
    pub fn rocks_writebatch_delete(b: *mut rocks_writebatch_t,
                                   key: *const ::std::os::raw::c_char,
                                   klen: usize);
}
extern "C" {
    pub fn rocks_writebatch_delete_cf(b: *mut rocks_writebatch_t,
                                      column_family:
                                          *mut rocks_column_family_handle_t,
                                      key: *const ::std::os::raw::c_char,
                                      klen: usize);
}
extern "C" {
    pub fn rocks_writebatch_deletev(b: *mut rocks_writebatch_t,
                                    num_keys: ::std::os::raw::c_int,
                                    keys_list:
                                        *const *const ::std::os::raw::c_char,
                                    keys_list_sizes: *const usize);
}
extern "C" {
    pub fn rocks_writebatch_deletev_cf(b: *mut rocks_writebatch_t,
                                       column_family:
                                           *mut rocks_column_family_handle_t,
                                       num_keys: ::std::os::raw::c_int,
                                       keys_list:
                                           *const *const ::std::os::raw::c_char,
                                       keys_list_sizes: *const usize);
}
extern "C" {
    pub fn rocks_writebatch_single_delete(b: *mut rocks_writebatch_t,
                                          key: *const ::std::os::raw::c_char,
                                          klen: usize);
}
extern "C" {
    pub fn rocks_writebatch_single_delete_cf(b: *mut rocks_writebatch_t,
                                             column_family:
                                                 *mut rocks_column_family_handle_t,
                                             key:
                                                 *const ::std::os::raw::c_char,
                                             klen: usize);
}
extern "C" {
    pub fn rocks_writebatch_delete_range(b: *mut rocks_writebatch_t,
                                         start_key:
                                             *const ::std::os::raw::c_char,
                                         start_key_len: usize,
                                         end_key:
                                             *const ::std::os::raw::c_char,
                                         end_key_len: usize);
}
extern "C" {
    pub fn rocks_writebatch_delete_range_cf(b: *mut rocks_writebatch_t,
                                            column_family:
                                                *mut rocks_column_family_handle_t,
                                            start_key:
                                                *const ::std::os::raw::c_char,
                                            start_key_len: usize,
                                            end_key:
                                                *const ::std::os::raw::c_char,
                                            end_key_len: usize);
}
extern "C" {
    pub fn rocks_writebatch_delete_rangev(b: *mut rocks_writebatch_t,
                                          num_keys: ::std::os::raw::c_int,
                                          start_keys_list:
                                              *const *const ::std::os::raw::c_char,
                                          start_keys_list_sizes: *const usize,
                                          end_keys_list:
                                              *const *const ::std::os::raw::c_char,
                                          end_keys_list_sizes: *const usize);
}
extern "C" {
    pub fn rocks_writebatch_delete_rangev_cf(b: *mut rocks_writebatch_t,
                                             column_family:
                                                 *mut rocks_column_family_handle_t,
                                             num_keys: ::std::os::raw::c_int,
                                             start_keys_list:
                                                 *const *const ::std::os::raw::c_char,
                                             start_keys_list_sizes:
                                                 *const usize,
                                             end_keys_list:
                                                 *const *const ::std::os::raw::c_char,
                                             end_keys_list_sizes:
                                                 *const usize);
}
extern "C" {
    pub fn rocks_writebatch_put_log_data(b: *mut rocks_writebatch_t,
                                         blob: *const ::std::os::raw::c_char,
                                         len: usize);
}
extern "C" {
    pub fn rocks_writebatch_iterate(b: *mut rocks_writebatch_t,
                                    state: *mut ::std::os::raw::c_void,
                                    put:
                                        ::std::option::Option<unsafe extern "C" fn(arg1:
                                                                                       *mut ::std::os::raw::c_void,
                                                                                   k:
                                                                                       *const ::std::os::raw::c_char,
                                                                                   klen:
                                                                                       usize,
                                                                                   v:
                                                                                       *const ::std::os::raw::c_char,
                                                                                   vlen:
                                                                                       usize)>,
                                    deleted:
                                        ::std::option::Option<unsafe extern "C" fn(arg1:
                                                                                       *mut ::std::os::raw::c_void,
                                                                                   k:
                                                                                       *const ::std::os::raw::c_char,
                                                                                   klen:
                                                                                       usize)>);
}
extern "C" {
    pub fn rocks_writebatch_data(b: *mut rocks_writebatch_t, size: *mut usize)
     -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn rocks_writebatch_set_save_point(b: *mut rocks_writebatch_t);
}
extern "C" {
    pub fn rocks_writebatch_rollback_to_save_point(b: *mut rocks_writebatch_t,
                                                   status:
                                                       *mut rocks_status_t);
}
extern "C" {
    pub fn rocks_iter_destroy(iter: *mut rocks_iterator_t);
}
extern "C" {
    pub fn rocks_iter_valid(iter: *const rocks_iterator_t)
     -> ::std::os::raw::c_uchar;
}
extern "C" {
    pub fn rocks_iter_seek_to_first(iter: *mut rocks_iterator_t);
}
extern "C" {
    pub fn rocks_iter_seek_to_last(iter: *mut rocks_iterator_t);
}
extern "C" {
    pub fn rocks_iter_seek(iter: *mut rocks_iterator_t,
                           k: *const ::std::os::raw::c_char, klen: usize);
}
extern "C" {
    pub fn rocks_iter_seek_for_prev(iter: *mut rocks_iterator_t,
                                    k: *const ::std::os::raw::c_char,
                                    klen: usize);
}
extern "C" {
    pub fn rocks_iter_next(iter: *mut rocks_iterator_t);
}
extern "C" {
    pub fn rocks_iter_prev(iter: *mut rocks_iterator_t);
}
extern "C" {
    pub fn rocks_iter_key(iter: *const rocks_iterator_t, klen: *mut usize)
     -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn rocks_iter_value(iter: *const rocks_iterator_t, vlen: *mut usize)
     -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn rocks_iter_get_status(iter: *const rocks_iterator_t,
                                 status: *mut rocks_status_t);
}
extern "C" {
    pub fn rocks_cache_create_lru(capacity: usize,
                                  num_shard_bits: ::std::os::raw::c_int,
                                  strict_capacity_limit:
                                      ::std::os::raw::c_char,
                                  high_pri_pool_ratio: f64)
     -> *mut rocks_cache_t;
}
extern "C" {
    pub fn rocks_cache_create_clock(capacity: usize,
                                    num_shard_bits: ::std::os::raw::c_int,
                                    strict_capacity_limit:
                                        ::std::os::raw::c_char)
     -> *mut rocks_cache_t;
}
extern "C" {
    pub fn rocks_cache_destroy(cache: *mut rocks_cache_t);
}
extern "C" {
    pub fn rocks_cache_set_capacity(cache: *mut rocks_cache_t,
                                    capacity: usize);
}
extern "C" {
    pub fn rocks_cache_get_capacity(cache: *mut rocks_cache_t) -> usize;
}
extern "C" {
    pub fn rocks_cache_get_usage(cache: *mut rocks_cache_t) -> usize;
}
extern "C" {
    pub fn rocks_cache_get_pinned_usage(cache: *mut rocks_cache_t) -> usize;
}
extern "C" {
    pub fn rocks_cache_name(cache: *mut rocks_cache_t)
     -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn free(p: *mut ::std::os::raw::c_void);
}
#[repr(C)]
#[derive(Copy)]
pub struct __va_list_tag {
    pub gp_offset: ::std::os::raw::c_uint,
    pub fp_offset: ::std::os::raw::c_uint,
    pub overflow_arg_area: *mut ::std::os::raw::c_void,
    pub reg_save_area: *mut ::std::os::raw::c_void,
}
impl Clone for __va_list_tag {
    fn clone(&self) -> Self { *self }
}
pub type __builtin_va_list = [__va_list_tag; 1usize];
