name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Installing lld
      shell: bash
      run: sudo apt install lld
    - name: Checkout submodules
      shell: bash
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --depth=1
    - name: Build
      run: cargo build --features static-link --verbose
      env:
        RUSTFLAGS: "-C link-arg=-fuse-ld=lld"
    - name: Run tests
      run: cargo test --tests --features static-link --no-fail-fast -- --test-threads 1
      env:
        RUSTFLAGS: "-C link-arg=-fuse-ld=lld"
